## Pandas Basic
* Data Structure
* 핵심기능
* 기술 통계 계산 및 요약
* 누락된 데이터 처리하기
* 계층적 색인
* 기타 주제

### When to use
* 자동적으로 혹은 명시적으로 축의 이름에 따라 데이터를 정렬할수 있는 자료구조
* 잘목 정렬된 데ㅐ이터의 일반적인 오류를 예방하고 다양한 소스에서 가져온 다양한 방시그로 색인되어 있는 데이터를 다룰수 있는 기능
* 통합된 시계열 기능
* 시계열 데이터와 비시계열 데이터를 함께 다룰 수 있는 통합 자료 구조
* 산술 연산과 한 축의 모든 값을 더하는 등의 데이터 축약연산은 축의 이름 같은 메타데이터로 전달될 수 있어야 함
* 누락된 데이터를 유연하게 처리
* SQL과 같은 일반 데이터베이스처럼 데이터를 합치고 관계 연산을 수행

### 자료 구조 소개

In [22]:
import numpy as np
import pandas as pd
from pandas import Series

#Series
obj = Series([4,7,-1,3])

In [23]:
obj

0    4
1    7
2   -1
3    3
dtype: int64

In [24]:
obj.values

array([ 4,  7, -1,  3])

In [25]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [26]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])

In [27]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [28]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [29]:
obj2['a']

-5

In [30]:
obj2['a'] = -6

In [31]:
obj2[['c','a','d']]

c    3
a   -6
d    4
dtype: int64

In [32]:
obj2

d    4
b    7
a   -6
c    3
dtype: int64

In [33]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [34]:
obj2 * 2

d     8
b    14
a   -12
c     6
dtype: int64

In [35]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.002479
c      20.085537
dtype: float64

In [36]:
'b' in obj2

True

In [37]:
'e' in obj2

False

In [38]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utash':5000}
obj3 = Series(sdata)

In [39]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utash      5000
dtype: int64

In [40]:
state = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(state)

In [41]:
obj4

0    California
1          Ohio
2        Oregon
3         Texas
dtype: object

In [42]:
obj4 = Series(sdata, index=state)

In [43]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [44]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [45]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [46]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [48]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utash      5000
dtype: int64

In [49]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [50]:
obj3*obj4

California             NaN
Ohio          1.225000e+09
Oregon        2.560000e+08
Texas         5.041000e+09
Utash                  NaN
dtype: float64

In [51]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [52]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -1
Ryan     3
dtype: int64

In [54]:
# dataframe
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],\
       'year':[2000, 2001, 2002, 2001, 2002], \
       'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}
data

{'pop': [1.5, 1.7, 3.6, 2.4, 2.9],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002]}

In [57]:
from pandas import DataFrame

frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [58]:
DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [59]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [60]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [62]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [63]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [64]:
frame2.ix['three']

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [65]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [66]:
frame2.iloc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [67]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: debt, dtype: object

In [68]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [74]:
frame2['debt'] = np.arange(5.)

In [75]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [76]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [77]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [78]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [79]:
del frame2['eastern']

In [80]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [81]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [82]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7, 2002:3.6}}

In [83]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [84]:
frame3 = DataFrame(pop)

In [85]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [86]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [87]:
DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [88]:
# index object
obj = Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [89]:
obj

a    0
b    1
c    2
dtype: int64

In [90]:
index[1:]

Index(['b', 'c'], dtype='object')

In [91]:
index[1] = 'd'

TypeError: Index does not support mutable operations

### Useful Things

In [92]:
# reindexing
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [98]:
obj2 = obj.reindex(['a', 'b', 'c', 'd','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [99]:
obj2 = obj.reindex(['a','b','c','d','e'], fill_value=0)

In [100]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [101]:
obj3 = Series(['blue', 'purple', 'yello'], index=[0,2,4])

In [102]:
obj3.reindex(range(6), method='ffill')  #fill the previous value (cf. bfill)

0      blue
1      blue
2    purple
3    purple
4     yello
5     yello
dtype: object

In [103]:
frame = DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'], columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [104]:
frame2 = frame.reindex(['a','b','c','d'])

In [105]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [107]:
# delete row or column
obj = Series(np.arange(5.), index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [108]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [109]:
# index, selet, skip
obj=Series(np.arange(4.), index=['a','b','c','d'])

In [110]:
obj['b']

1.0

In [111]:
obj[1]

1.0

In [112]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj['b':'c'] = 5

In [117]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [118]:
# arithmatic and sorting
df1 = DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [119]:
df2 = DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [120]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [121]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [122]:
df1.reindex(columns=df2.columns, fill_value=0) # arithmatic. add, sub, div, mul

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [123]:
# DataFrame and Series Operations
arr = np.arange(12.).reshape((3,4))
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [124]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [125]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [129]:
frame = DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), \
                 index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [127]:
series = frame.ix(0)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [131]:
series = frame.loc['Utah']
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [132]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [133]:
frame = DataFrame(np.random.randn(4,3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.320825 -1.119495  0.343952
Ohio   -0.145704  0.649395  0.640325
Texas  -0.766009 -0.484105  2.153190
Oregon  0.368931 -0.908033  0.525219

In [134]:
np.abs(frame)

b         d         e
Utah    1.320825  1.119495  0.343952
Ohio    0.145704  0.649395  0.640325
Texas   0.766009  0.484105  2.153190
Oregon  0.368931  0.908033  0.525219

In [135]:
f = lambda x:x.max() - x.min()
frame.apply(f)

b    2.086835
d    1.768890
e    1.809238
dtype: float64

In [136]:
frame.apply(f, axis=1)

Utah      2.440321
Ohio      0.795098
Texas     2.919200
Oregon    1.433252
dtype: float64

In [138]:
# sort and order
obj = Series(range(4), index=list('dabc'))

In [139]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [140]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [144]:
obj.order()

AttributeError: 'Series' object has no attribute 'order'

## Descriptive Statistics

## NaN handling

In [145]:
from numpy import nan as NA

data = DataFrame([[1., 6.5, 3.],[1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [146]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [147]:
cleaned = data.dropna()
cleaned

0    1    2
0  1.0  6.5  3.0

In [148]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [149]:
data.fillna(0)

0    1    2
0  1.0  6.5  3.0
1  1.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  6.5  3.0

In [153]:
data.fillna({1:0.5, 2:-1})

0    1    2
0  1.0  6.5  3.0
1  1.0  0.5 -1.0
2  NaN  0.5 -1.0
3  NaN  6.5  3.0

In [155]:
# hierachical indexing
frame = DataFrame(np.arange(12).reshape((4,3)), index=[['a','a','b','b'], [1,2,1,2]],\
                                                      columns=[['Ohio', 'Ohio', 'Colorado'], \
                                                              ['Green', 'Red', 'Green']])

In [156]:
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11